USE [master]
GO

/****** Object:  Database [PORTALNR]    Script Date: 15/05/2023 23:48:16 ******/
CREATE DATABASE [PORTALNR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PORTALNR', FILENAME = N'H:\DB\PORTALNR.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PORTALNR_log', FILENAME = N'H:\DB\PORTALNR_log.ldf' , SIZE = 84416KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PORTALNR] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PORTALNR].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PORTALNR] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PORTALNR] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PORTALNR] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PORTALNR] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PORTALNR] SET ARITHABORT OFF 
GO

ALTER DATABASE [PORTALNR] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PORTALNR] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [PORTALNR] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PORTALNR] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PORTALNR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PORTALNR] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PORTALNR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PORTALNR] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PORTALNR] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PORTALNR] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PORTALNR] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PORTALNR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PORTALNR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PORTALNR] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PORTALNR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PORTALNR] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PORTALNR] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PORTALNR] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PORTALNR] SET RECOVERY FULL 
GO

ALTER DATABASE [PORTALNR] SET  MULTI_USER 
GO

ALTER DATABASE [PORTALNR] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PORTALNR] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PORTALNR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PORTALNR] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PORTALNR] SET  READ_WRITE 
GO


